/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2;

import java.util.ArrayList;

/**
 *
 * @author jenniferbueso
 */
public class AgregarPlan extends javax.swing.JFrame {
    private Tigo tigoFunciones;
    ArrayList<Plan> planesTipo;
    
    public AgregarPlan(ArrayList<Plan> planesTipoExterno) {
        tigoFunciones = new Tigo(planesTipoExterno);
        planesTipo = planesTipoExterno;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TipoPlanBox = new javax.swing.JComboBox<>();
        ExtraField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        NumeroTelefonoField = new javax.swing.JTextField();
        BotonRegresar = new javax.swing.JLabel();
        BotonAgregar = new javax.swing.JLabel();
        ExtraLabel = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TipoPlanBox.setBackground(new java.awt.Color(255, 222, 89));
        TipoPlanBox.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        TipoPlanBox.setForeground(new java.awt.Color(0, 0, 0));
        TipoPlanBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "IPHONE", "SAMSUNG" }));
        TipoPlanBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPlanBoxActionPerformed(evt);
            }
        });
        jPanel1.add(TipoPlanBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 398, 180, 40));

        ExtraField.setBackground(new java.awt.Color(255, 222, 89));
        ExtraField.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        ExtraField.setForeground(new java.awt.Color(0, 0, 0));
        ExtraField.setBorder(null);
        jPanel1.add(ExtraField, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 399, 320, 40));

        NombreField.setBackground(new java.awt.Color(255, 222, 89));
        NombreField.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        NombreField.setForeground(new java.awt.Color(0, 0, 0));
        NombreField.setBorder(null);
        jPanel1.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 271, 320, 40));

        NumeroTelefonoField.setBackground(new java.awt.Color(255, 222, 89));
        NumeroTelefonoField.setFont(new java.awt.Font("InaiMathi", 1, 18)); // NOI18N
        NumeroTelefonoField.setForeground(new java.awt.Color(0, 0, 0));
        NumeroTelefonoField.setBorder(null);
        jPanel1.add(NumeroTelefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 271, 320, 40));

        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 70, 50));

        BotonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 180, 60));

        ExtraLabel.setBackground(new java.awt.Color(81, 39, 33));
        ExtraLabel.setFont(new java.awt.Font("Grantha Sangam MN", 1, 20)); // NOI18N
        ExtraLabel.setForeground(new java.awt.Color(81, 39, 33));
        ExtraLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ExtraLabel.setText("Extra:");
        ExtraLabel.setToolTipText("");
        jPanel1.add(ExtraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 359, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/AgregarPlan.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
       MenuPrincipal menuPrincipal = new MenuPrincipal(planesTipo);
       menuPrincipal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarMouseClicked
        int numeroTelefono = Integer.valueOf(NumeroTelefonoField.getText());
        String nombre = NombreField.getText();
        String extra = ExtraField.getText();
        String tipo = TipoPlanBox.getSelectedItem().toString();
        
        tigoFunciones.agregarPlan(numeroTelefono, nombre, extra, tipo);
    }//GEN-LAST:event_BotonAgregarMouseClicked

    private void TipoPlanBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPlanBoxActionPerformed
        int mostrar = TipoPlanBox.getSelectedIndex();
        
        if (mostrar == 0) {
            ExtraLabel.setText("EXTRA:");
        } else if (mostrar == 1) {
            ExtraLabel.setText("EMAIL:");
        } else if (mostrar == 2) {
            ExtraLabel.setText("PIN:");
        }
    }//GEN-LAST:event_TipoPlanBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlan(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregar;
    private javax.swing.JLabel BotonRegresar;
    private javax.swing.JTextField ExtraField;
    private javax.swing.JLabel ExtraLabel;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField NombreField;
    private javax.swing.JTextField NumeroTelefonoField;
    private javax.swing.JComboBox<String> TipoPlanBox;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
