/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jenniferbueso
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Tigo tigoFunciones;
    ArrayList<Plan> planesTipo;

    
    public MenuPrincipal(ArrayList<Plan> planesTipoExterno) {
        tigoFunciones = new Tigo();
        
        if (planesTipoExterno != null) {
            planesTipo = planesTipoExterno;
        } else {
            planesTipo = new ArrayList<>();
        }

        initComponents();
        
        if (planesTipo.isEmpty()) {
            System.out.println("El ArrayList planesTipo está vacío.");
        } else {
            System.out.println("Contenido actual de planesTipo:");
            for (Plan plan : planesTipo) {
                System.out.println(plan.imprimir());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JLabel();
        BotonListar = new javax.swing.JLabel();
        BotonAgregarAmigo = new javax.swing.JLabel();
        BotonPagoPlan = new javax.swing.JLabel();
        BotonAgregarPlan = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
        });
        jPanel1.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 240, 70));

        BotonListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonListarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 240, 70));

        BotonAgregarAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarAmigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarAmigoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarAmigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 240, 70));

        BotonPagoPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonPagoPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPagoPlanMouseClicked(evt);
            }
        });
        jPanel1.add(BotonPagoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 240, 70));

        BotonAgregarPlan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarPlanMouseClicked(evt);
            }
        });
        jPanel1.add(BotonAgregarPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 240, 70));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elementos/MenuPrincipal.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarPlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarPlanMouseClicked
        AgregarPlan agregarPlan = new AgregarPlan(planesTipo);
        agregarPlan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarPlanMouseClicked

    private void BotonPagoPlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPagoPlanMouseClicked
        PagoPlan pagoPlan = new PagoPlan(planesTipo);
        pagoPlan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPagoPlanMouseClicked

    private void BotonAgregarAmigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarAmigoMouseClicked
        AgregarAmigo agregarAmigo = new AgregarAmigo(planesTipo);
        agregarAmigo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonAgregarAmigoMouseClicked

    private void BotonListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonListarMouseClicked
        Listar listar = new Listar(planesTipo);
        listar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonListarMouseClicked

    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        int opcionSalir = JOptionPane.showConfirmDialog(null, "¿Desea salir del programa?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcionSalir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_BotonSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonAgregarAmigo;
    private javax.swing.JLabel BotonAgregarPlan;
    private javax.swing.JLabel BotonListar;
    private javax.swing.JLabel BotonPagoPlan;
    private javax.swing.JLabel BotonSalir;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
